### ISSUE TITLE
In validation_error: Only the following parameters are allowed: app_id, currency

### ISSUE THREAD

**Issue by xChr11s** [PaxxPatriot/cheapbot#2]
Hey,
Thank you for your work in this project.
I tried to get it running but I get this error after around 30 secs:

> Task exception was never retrieved
> future: <Task finished name='Task-47' coro=<AsyncClient._handle_eio_message() done, defined at C:\Users\XX\Desktop\cheapbot\Python\lib\site-packages\socketio\asyncio_client.py:505> exception=HTTPException('400 Bad Request): \nIn validation_error: Only the following parameters are allowed: app_id, currency')>
> Traceback (most recent call last):
>   File "C:\Users\XX\Desktop\cheapbot\Python\lib\site-packages\socketio\asyncio_client.py", line 522, in _handle_eio_message
>     await self._handle_event(pkt.namespace, pkt.id, pkt.data)
>   File "C:\Users\XX\Desktop\cheapbot\Python\lib\site-packages\socketio\asyncio_client.py", line 381, in _handle_event
>     r = await self._trigger_event(data[0], namespace, *data[1:])
>   File "C:\Users\XX\Desktop\cheapbot\Python\lib\site-packages\socketio\asyncio_client.py", line 441, in _trigger_event
>     ret = await handler(*args)
>   File "C:\Users\XX\Desktop\cheapbot\cheapbot.py", line 25, in on_sale_feed
>     sales = await skinport_client.get_sales_history(s.market_hash_name)
>   File "C:\Users\XX\Desktop\cheapbot\Python\lib\site-packages\skinport\client.py", line 285, in get_sales_history
>     data = await self.http.get_sales_history(params=params)
>   File "C:\Users\XX\Desktop\cheapbot\Python\lib\site-packages\skinport\http.py", line 115, in get_sales_history
>     return await self.request(Route("GET", "/sales/history"), **parameters)
>   File "C:\Users\XX\Desktop\cheapbot\Python\lib\site-packages\skinport\http.py", line 109, in request
>     raise HTTPException(response, data)
> skinport.errors.HTTPException: 400 Bad Request):
> In validation_error: Only the following parameters are allowed: app_id, currency

I can't find any problem at the mentioned lines with the parameters.
Do you have any idea?

Kind regards

Chris

**Comment by PaxxPatriot** [comment]
This is very interesting and even the sample curl command from the [Skinport Docs](https://docs.skinport.com/#history) gives this error.

The workaround is using the endpoint without a `market_hash_name`. Therefore you would have to adjust the `client.py` of the skinport.py library like this:

```
    params = {
        "app_id": app_id,
        "currency": currency.value,
    }
    data = await self.http.get_sales_history(params=params)
    return [ItemWithSales(data=sale) for sale in data]
```
You then get the whole Sale History for many, many items. Would be advisable to cache it somewhere because you get rate-limited really fast. So for now the cheapbot is broken. :(

I would do it also in the library itself but can't until Monday unfortunately.
